### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by axlider** [tuckerconnelly/react-stack-nav-examples#1]
On android i get an error:
- "unknown plugin" "transform-react-remove-prop-types"

the web version runs fine 
- in Firefox 50.1.0. 

the menu button is not visible in:
- Chrome Version 36.0.1985.143 
- Internet Explorer 11

**Comment by tuckerconnelly** [comment]
Hey thanks for the issue--these guys are on master and there were a boat-load of breaking changes recently. I'll take a look soon.

**Comment by tuckerconnelly** [comment]
Hey thanks again. IE11 and Chrome 36 were legit broken, not just from old repos.

Got them both working on Galaxy S5, all the latest major browsers, and IE11 and Chrome 36.

Let me know if you have any more issues :)

Edit: Make sure you remove your node_modules and re-install using npm, not yarn, the first time.
